config/routes.rb
<<<<<<< HEAD
Rails.application.routes.draw do
  # Roles Management
  TheRoleManagementPanel::Routes.mixin(self)

  # Errors Routes
  match '/403', to: 'errors#forbidden', via: :all, as: :forbidden
  match '/404', to: 'errors#file_not_found', via: :all, as: :file_not_found
  match '/422', to: 'errors#unprocessable', via: :all, as: :unprocessable
  match '/500', to: 'errors#internal_server_error', via: :all, as: :internal_server_error

  # Locale Scope
  scope 'locale' do
    get 'change/:country' => 'localize#change', as: :locale_change
    get 'states_from/:country' => 'localize#states_from', as: :states_from
    get 'cities_from/:country/:state' => 'localize#cities_from', as: :cities_from
  end

  # DeviseUser sessions
  devise_for :users,
             controllers: {
                 unlocks: 'users/unlocks',
                 sessions: 'users/sessions',
                 passwords: 'users/passwords',
                 registrations: 'users/registrations',
                 confirmations: 'users/confirmations',
                 omniauth_callbacks: 'users/omniauth_callbacks'
             }

  scope "/admin" do
    resources :users
  end

  scope "/subjects" do
    resources :knowledge_areas
  end

  # Not Persistence actions
  get 'dashboard', to: 'dashboard#index', as: :dashboard

  # Resources (CRUDs)
  resources :schools
  resources :subjects do
    post 'sign' => 'subjects#sign'
  end
  resources :subscriptions

  # Root route
  root to: 'users#index'
=======
Rails.application.routes.draw do
  # Roles Management
  TheRoleManagementPanel::Routes.mixin(self)

  # Errors Routes
  match '/403', to: 'errors#forbidden', via: :all, as: :forbidden
  match '/404', to: 'errors#file_not_found', via: :all, as: :file_not_found
  match '/422', to: 'errors#unprocessable', via: :all, as: :unprocessable
  match '/500', to: 'errors#internal_server_error', via: :all, as: :internal_server_error

  # Locale Scope
  scope 'locale' do
    get 'change/:country' => 'localize#change', as: :locale_change
    get 'states_from/:country' => 'localize#states_from', as: :states_from
    get 'cities_from/:country/:state' => 'localize#cities_from', as: :cities_from
  end

  # DeviseUser sessions
  devise_for :users,
             controllers: {
                 unlocks: 'users/unlocks',
                 sessions: 'users/sessions',
                 passwords: 'users/passwords',
                 registrations: 'users/registrations',
                 confirmations: 'users/confirmations',
                 omniauth_callbacks: 'users/omniauth_callbacks'
             }

  scope "/admin" do
    resources :users
  end

  scope "/subjects" do
    resources :knowledge_areas
  end

  # Not Persistence actions
  get 'dashboard', to: 'dashboard#index', as: :dashboard

  # Resources (CRUDs)
  resources :schools
  resources :subjects do
    post 'sign' => 'subjects#sign'
  end
  resources :subscriptions

  # Root route
  root to: 'users#index'
>>>>>>> 34166a1067dc45e0339bcbf35c4f8978d91dd5f3
end

app/views/layouts/partials/components/sidebar/resources_actions/_admin.html.slim
ul.nav
  - if admin?
    li class=(('active ' if current_page?(admin_roles_path)))
      a href="#{admin_roles_path}"
        i.ion-ios-bookmarks
        p
          =t('actions.roles.index')

  / li class=(('active ' if current_page?(dashboard_path) || current_page?(root_path) || current_page_includes?('dashboard')))
  /   a href="#{dashboard_path}"
  /     i.ion-ios-pie
  /     p
  /       =t('actions.dashboard.name')

  li class=(('active ' if current_page?(users_path) || current_page_includes?('users') || current_page?(root_path)))
    a href="#{users_path}"
      i.ion-ios-people
      p
        =t('actions.users.name')

  li class=(('active ' if current_page?(schools_path) || current_page_includes?('schools') ))
    a href="#{schools_path}"
      i.ion-university
      p
        =t('actions.schools.name')

  li class=(('active ' if current_page?(subjects_path) || current_page_includes?('subjects') ))
    a data-toggle="collapse" href="#subjectActions" aria-expanded=(('true ' if current_page?(subjects_path) || current_page_includes?('subjects') ))
      i.ion-briefcase
      p
        =t('actions.subjects.name')
        b.caret
    #subjectActions.collapse class=(('collapse in' if current_page?(subjects_path) || current_page_includes?('subjects'))) aria-expanded=(('true ' if current_page?(subjects_path) || current_page_includes?('subjects') ))
      ul.nav
        li
          a href="#{knowledge_areas_path}"
            / i.ion-android-apps
            =t('actions.knowledge_areas.name')
        li
          a href="#{subjects_path}"
            / i.ion-university
            =t('actions.subjects.action_name')

app/views/layouts/partials/components/sidebar/resources_actions/_user.html.slim
<<<<<<< HEAD
ul.nav
  li class=(('active ' if current_page?(subjects_path))) aria-expanded=(('true ' if current_page?(subjects_path) || current_page_includes?('subjects') ))
    a data-toggle="collapse" href="#subjectsActions"
      i.ion-briefcase
      p
        =t('actions.subjects.name')
        b.caret
    #subjectsActions.collapse
      ul.nav
        li
          a href="#{subjects_path}"
            =t('actions.subjects.action_name')
  li class=(('active ' if current_page?(subscriptions_path))) aria-expanded=(('true ' if current_page?(subscriptions_path) || current_page_includes?('subscriptions_path') ))
    a data-toggle="collapse" href="#subscriptionsActions"
      i.ion-chatbox-working
      p
        =t('actions.subscriptions.name')
        b.caret
    #subscriptionsActions.collapse
      ul.nav
        li
          a href="#{subscriptions_path}"
            =t('actions.subscriptions.action_name')


  / li class=(('active ' if current_page?(subjects_path))) aria-expanded=(('true ' if current_page?(subjects_path) || current_page_includes?('subjects') ))
  /   a data-toggle="collapse" href="#subjectsActions"
  /     i.ion-briefcase
  /     p
  /       =t('actions.subjects.name')
  /       b.caret
  /   #subjectsActions.collapse
  /     ul.nav
  /       li
  /         a href="#{subjects_path}"
=======
ul.nav
  li class=(('active ' if current_page?(subjects_path))) aria-expanded=(('true ' if current_page?(subjects_path) || current_page_includes?('subjects') ))
    a data-toggle="collapse" href="#subjectsActions"
      i.ion-briefcase
      p
        =t('actions.subjects.name')
        b.caret
    #subjectsActions.collapse
      ul.nav
        li
          a href="#{subjects_path}"
            =t('actions.subjects.action_name')
  li class=(('active ' if current_page?(subscriptions_path))) aria-expanded=(('true ' if current_page?(subscriptions_path) || current_page_includes?('subscriptions_path') ))
    a data-toggle="collapse" href="#subscriptionsActions"
      i.ion-chatbox-working
      p
        =t('actions.subscriptions.name')
        b.caret
    #subscriptionsActions.collapse
      ul.nav
        li
          a href="#{subscriptions_path}"
            =t('actions.subscriptions.action_name')


  / li class=(('active ' if current_page?(subjects_path))) aria-expanded=(('true ' if current_page?(subjects_path) || current_page_includes?('subjects') ))
  /   a data-toggle="collapse" href="#subjectsActions"
  /     i.ion-briefcase
  /     p
  /       =t('actions.subjects.name')
  /       b.caret
  /   #subjectsActions.collapse
  /     ul.nav
  /       li
  /         a href="#{subjects_path}"
>>>>>>> 34166a1067dc45e0339bcbf35c4f8978d91dd5f3
  /           =t('actions.subjects.action_name')