config/routes.rb
<<<<<<< HEAD
Rails.application.routes.draw do
  # Roles Management
  TheRoleManagementPanel::Routes.mixin(self)

  # Errors Routes
  match '/403', to: 'errors#forbidden', via: :all, as: :forbidden
  match '/404', to: 'errors#file_not_found', via: :all, as: :file_not_found
  match '/422', to: 'errors#unprocessable', via: :all, as: :unprocessable
  match '/500', to: 'errors#internal_server_error', via: :all, as: :internal_server_error

  # Locale Scope
  scope 'locale' do
    get 'change/:country' => 'localize#change', as: :locale_change
    get 'states_from/:country' => 'localize#states_from', as: :states_from
    get 'cities_from/:country/:state' => 'localize#cities_from', as: :cities_from
  end

  # DeviseUser sessions
  devise_for :users,
             controllers: {
                 unlocks: 'users/unlocks',
                 sessions: 'users/sessions',
                 passwords: 'users/passwords',
                 registrations: 'users/registrations',
                 confirmations: 'users/confirmations',
                 omniauth_callbacks: 'users/omniauth_callbacks'
             }

  scope "/admin" do
    resources :users
  end

  scope "/subjects" do
    resources :knowledge_areas
  end

  # Not Persistence actions
  get 'dashboard', to: 'dashboard#index', as: :dashboard

  # Resources (CRUDs)
  resources :schools
  resources :subjects do
    post 'sign' => 'subjects#sign'
  end
  resources :subscriptions

  # Root route
  root to: 'users#index'
=======
Rails.application.routes.draw do
  # Roles Management
  TheRoleManagementPanel::Routes.mixin(self)

  # Errors Routes
  match '/403', to: 'errors#forbidden', via: :all, as: :forbidden
  match '/404', to: 'errors#file_not_found', via: :all, as: :file_not_found
  match '/422', to: 'errors#unprocessable', via: :all, as: :unprocessable
  match '/500', to: 'errors#internal_server_error', via: :all, as: :internal_server_error

  # Locale Scope
  scope 'locale' do
    get 'change/:country' => 'localize#change', as: :locale_change
    get 'states_from/:country' => 'localize#states_from', as: :states_from
    get 'cities_from/:country/:state' => 'localize#cities_from', as: :cities_from
  end

  # DeviseUser sessions
  devise_for :users,
             controllers: {
                 unlocks: 'users/unlocks',
                 sessions: 'users/sessions',
                 passwords: 'users/passwords',
                 registrations: 'users/registrations',
                 confirmations: 'users/confirmations',
                 omniauth_callbacks: 'users/omniauth_callbacks'
             }

  scope "/admin" do
    resources :users
  end

  scope "/subjects" do
    resources :knowledge_areas
  end

  # Not Persistence actions
  get 'dashboard', to: 'dashboard#index', as: :dashboard

  # Resources (CRUDs)
  resources :schools
  resources :subjects do
    post 'sign' => 'subjects#sign'
  end
  resources :subscriptions

  # Root route
  root to: 'users#index'
>>>>>>> 34166a1067dc45e0339bcbf35c4f8978d91dd5f3
end

app/models/subscription.rb
<<<<<<< HEAD
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :subject

  before_save :prevent_duplication
  before_create :prevent_duplication

  attr_accessor :duplicated_association

  def duplicated?
    Subscription.where(user_id: self.user_id, subject_id: self.subject_id).take.nil?
  end

  def self.duplicated?(user_id, subject_id)
    Subscription.where(user_id: user_id, subject_id: subject_id).take.nil?
  end

  def prevent_duplication
    subscription = Subscription.duplicated?(self.attributes['user_id'], self.attributes['subject_id'])
    unless subscription.nil?
      errors.add(:duplicated_association, :blank, message: "true")
    end
  end
end
=======
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :subject

  before_save :prevent_duplication
  before_create :prevent_duplication

  attr_accessor :duplicated_association

  def duplicated?
    Subscription.where(user_id: self.user_id, subject_id: self.subject_id).take.nil?
  end

  def self.duplicated?(user_id, subject_id)
    Subscription.where(user_id: user_id, subject_id: subject_id).take.nil?
  end

  def prevent_duplication
    subscription = Subscription.duplicated?(self.attributes['user_id'], self.attributes['subject_id'])
    unless subscription.nil?
      errors.add(:duplicated_association, :blank, message: "true")
    end
  end
end
>>>>>>> 34166a1067dc45e0339bcbf35c4f8978d91dd5f3

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_subscription, only: [:show, :edit, :update, :destroy]

  # GET /subscriptions
  # GET /subscriptions.json
  def index
    @subscriptions = Subscription.all
  end

  # GET /subscriptions/1
  # GET /subscriptions/1.json
  def show
  end

  # GET /subscriptions/new
  def new
    @subscription = Subscription.new
  end

  # GET /subscriptions/1/edit
  def edit
  end

  # POST /subscriptions
  # POST /subscriptions.json
  def create
    @subscription = Subscription.new(subscription_params)

    respond_to do |format|
      if @subscription.save
        format.html { redirect_to @subscription, notice: 'Subscription was successfully created.' }
        format.json { render :show, status: :created, location: @subscription }
      else
        format.html { render :new }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscriptions/1
  # PATCH/PUT /subscriptions/1.json
  def update
    respond_to do |format|
      if @subscription.update(subscription_params)
        format.html { redirect_to @subscription, notice: 'Subscription was successfully updated.' }
        format.json { render :show, status: :ok, location: @subscription }
      else
        format.html { render :edit }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1
  # DELETE /subscriptions/1.json
  def destroy
    @subscription.destroy
    respond_to do |format|
      format.html { redirect_to subscriptions_url, notice: 'Subscription was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscription
      @subscription = Subscription.find(params[:id])
      @current_obj = @subscription
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subscription_params
      params.require(:subscription).permit(:access_type, :user_id, :subject_id)
    end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_form.html.slim
= form_for @subscription do |f|
  - if @subscription.errors.any?
    #error_explanation
      h2 = "#{pluralize(@subscription.errors.count, "error")} prohibited this subscription from being saved:"
      ul
        - @subscription.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :access_type
    = f.text_field :access_type
  .field
    = f.label :user
    = f.text_field :user
  .field
    = f.label :subject
    = f.text_field :subject
  .actions = f.submit

app/views/subscriptions/edit.html.slim
h1 Editing subscription

== render 'form'

=> link_to 'Show', @subscription
'|
=< link_to 'Back', subscriptions_path


app/views/subscriptions/index.html.slim
<<<<<<< HEAD
.container-fluid
  .row
    table#data.table.col-md-12.col-xs-12
      thead
        tr
          th =t('activerecord.attributes.subscription.subject_name')
          th =t('activerecord.attributes.subscription.subject_description')
          th =t('activerecord.attributes.subscription.subject_workload')
          th =t('activerecord.attributes.subscription.subject_online_link')
          / th =t('activerecord.attributes.subject.class_schedule')
          th
          th
          th

      tbody
        - @subscriptions.each do |subscription|
          tr
            td =subscription.subject.name
            td =subscription.subject.description
            td =subscription.subject.workload
            td =subscription.subject.online_link
            / td =subject.class_schedule
            td =link_to subject do
              i.fa.fa-eye
            td =link_to edit_subject_path(subject) do
              i.fa.fa-edit
            td =link_to subject, data: {confirm: 'Você tem certeza disso? Esta ação não poderá ser desfeita!'}, method: :delete do
              i.fa.fa-trash.text-danger


javascript:
    //"//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Portuguese.json"
    $(document).ready(function () {
        $('#data').DataTable({
            "language": {
                "url": "/Portuguese.json"
            }
        });
=======
.container-fluid
  .row
    table#data.table.col-md-12.col-xs-12
      thead
        tr
          th =t('activerecord.attributes.subscription.subject_name')
          th =t('activerecord.attributes.subscription.subject_description')
          th =t('activerecord.attributes.subscription.subject_workload')
          th =t('activerecord.attributes.subscription.subject_online_link')
          / th =t('activerecord.attributes.subject.class_schedule')
          th
          th
          th

      tbody
        - @subscriptions.each do |subscription|
          tr
            td =subscription.subject.name
            td =subscription.subject.description
            td =subscription.subject.workload
            td =subscription.subject.online_link
            / td =subject.class_schedule
            td =link_to subject do
              i.fa.fa-eye
            td =link_to edit_subject_path(subject) do
              i.fa.fa-edit
            td =link_to subject, data: {confirm: 'Você tem certeza disso? Esta ação não poderá ser desfeita!'}, method: :delete do
              i.fa.fa-trash.text-danger


javascript:
    //"//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Portuguese.json"
    $(document).ready(function () {
        $('#data').DataTable({
            "language": {
                "url": "/Portuguese.json"
            }
        });
>>>>>>> 34166a1067dc45e0339bcbf35c4f8978d91dd5f3
    });

app/views/subscriptions/new.html.slim
h1 New subscription

== render 'form'

= link_to 'Back', subscriptions_path

app/views/subscriptions/show.html.slim
p#notice = notice

p
  strong Access type:
  = @subscription.access_type
p
  strong User:
  = @subscription.user
p
  strong Subject:
  = @subscription.subject

=> link_to 'Edit', edit_subscription_path(@subscription)
'|
=< link_to 'Back', subscriptions_path