config/routes.rb
<<<<<<< HEAD
Rails.application.routes.draw do
  # Roles Management
  TheRoleManagementPanel::Routes.mixin(self)

  # Errors Routes
  match '/403', to: 'errors#forbidden', via: :all, as: :forbidden
  match '/404', to: 'errors#file_not_found', via: :all, as: :file_not_found
  match '/422', to: 'errors#unprocessable', via: :all, as: :unprocessable
  match '/500', to: 'errors#internal_server_error', via: :all, as: :internal_server_error

  # Locale Scope
  scope 'locale' do
    get 'change/:country' => 'localize#change', as: :locale_change
    get 'states_from/:country' => 'localize#states_from', as: :states_from
    get 'cities_from/:country/:state' => 'localize#cities_from', as: :cities_from
  end

  # DeviseUser sessions
  devise_for :users,
             controllers: {
                 unlocks: 'users/unlocks',
                 sessions: 'users/sessions',
                 passwords: 'users/passwords',
                 registrations: 'users/registrations',
                 confirmations: 'users/confirmations',
                 omniauth_callbacks: 'users/omniauth_callbacks'
             }

  scope "/admin" do
    resources :users
  end

  scope "/subjects" do
    resources :knowledge_areas
  end

  # Not Persistence actions
  get 'dashboard', to: 'dashboard#index', as: :dashboard

  # Resources (CRUDs)
  resources :schools
  resources :subjects do
    post 'sign' => 'subjects#sign'
  end
  resources :subscriptions

  # Root route
  root to: 'users#index'
=======
Rails.application.routes.draw do
  # Roles Management
  TheRoleManagementPanel::Routes.mixin(self)

  # Errors Routes
  match '/403', to: 'errors#forbidden', via: :all, as: :forbidden
  match '/404', to: 'errors#file_not_found', via: :all, as: :file_not_found
  match '/422', to: 'errors#unprocessable', via: :all, as: :unprocessable
  match '/500', to: 'errors#internal_server_error', via: :all, as: :internal_server_error

  # Locale Scope
  scope 'locale' do
    get 'change/:country' => 'localize#change', as: :locale_change
    get 'states_from/:country' => 'localize#states_from', as: :states_from
    get 'cities_from/:country/:state' => 'localize#cities_from', as: :cities_from
  end

  # DeviseUser sessions
  devise_for :users,
             controllers: {
                 unlocks: 'users/unlocks',
                 sessions: 'users/sessions',
                 passwords: 'users/passwords',
                 registrations: 'users/registrations',
                 confirmations: 'users/confirmations',
                 omniauth_callbacks: 'users/omniauth_callbacks'
             }

  scope "/admin" do
    resources :users
  end

  scope "/subjects" do
    resources :knowledge_areas
  end

  # Not Persistence actions
  get 'dashboard', to: 'dashboard#index', as: :dashboard

  # Resources (CRUDs)
  resources :schools
  resources :subjects do
    post 'sign' => 'subjects#sign'
  end
  resources :subscriptions

  # Root route
  root to: 'users#index'
>>>>>>> 34166a1067dc45e0339bcbf35c4f8978d91dd5f3
end

app/models/school.rb
class School < ApplicationRecord
  belongs_to :user
  has_many :users
  attr_accessor :coord

  def coordinator
    return self.coord if self.coord
    _coordinator = self.users.where(role: Role.where(name: :coordinator)).take
    self.coord = _coordinator
    if _coordinator.nil?
      u = User.new
      u.full_name = 'sem coordenador'
      self.coord = u
    else
      self.coord = _coordinator
    end

    self.coord
  end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: [:show, :edit, :update, :destroy]

  # GET /schools
  # GET /schools.json
  def index
    @schools = School.all
  end

  # GET /schools/1
  # GET /schools/1.json
  def show
  end

  # GET /schools/new
  def new
    @school = School.new
  end

  # GET /schools/1/edit
  def edit
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(school_params)

    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: 'School was successfully created.' }
        format.json { render :show, status: :created, location: @school }
      else
        format.html { render :new }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schools/1
  # PATCH/PUT /schools/1.json
  def update
    respond_to do |format|
      if @school.update(school_params)
        format.html { redirect_to @school, notice: 'School was successfully updated.' }
        format.json { render :show, status: :ok, location: @school }
      else
        format.html { render :edit }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school.destroy
    respond_to do |format|
      format.html { redirect_to schools_url, notice: 'School was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school
      @school = School.find(params[:id])
      @current_obj = @school
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def school_params
      base_params = params.require(:school).permit(:name, :code)
      base_params[:user_id] = @current_user.id
      base_params
    end
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/_form.html.slim
=form_for @school do |f|
  - if @school.errors.any?
    #error_explanation
      h2 = "#{pluralize(@school.errors.count, "erro(s)")} proibiram esta Instituição de Ensino de ser registrada:"
      ul
        - @school.errors.full_messages.each do |message|
          li = message

  .form-group
    =f.label :name
    =f.text_field :name, class: 'form-control', required: true
  .form-group
    =f.label :code
    =f.text_field :code, class: 'form-control', required: true
  .form-group
    =f.label :total_rooms
    =f.text_field :total_rooms, class: 'form-control'
  .form-group
    =f.label :used_rooms
    =f.text_field :used_rooms, class: 'form-control'
  .form-group
    =f.label :amount_employees
    =f.text_field :amount_employees, class: 'form-control'

  .footer.text-center
  =f.submit t("actions.#{params[:controller]}.button.#{params[:action]}"), class: 'btn btn-fill btn-info btn-wd'

app/views/schools/index.html.slim
<<<<<<< HEAD
.container-fluid
  .row
    table#data.table.col-md-12.col-xs-12
      thead
        tr
          th =t('activerecord.attributes.school.name')
          th =t('activerecord.attributes.school.code')
          / th =t('activerecord.attributes.school.user')
          th =t('activerecord.attributes.school.total_rooms')
          th =t('activerecord.attributes.school.used_rooms')
          th =t('activerecord.attributes.school.amount_employees')
          th =t('activerecord.attributes.school.technical_or_high_school')
          th
          th
          th

      tbody
        - @schools.each do |school|
          tr
            td =school.name
            td =school.code
            / td =school.user.first_name
            td =school.total_rooms
            td =school.used_rooms
            td =school.amount_employees
            td
              -if school.technical_or_high_school
                p sim
              -else
                p não
            td =link_to school do
              i.fa.fa-eye
            td =link_to edit_school_path(school) do
              i.fa.fa-edit
            td =link_to school, data: {confirm: 'Você tem certeza disso? Esta ação não poderá ser desfeita!'}, method: :delete do
              i.fa.fa-trash.text-danger


javascript:
    //"//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Portuguese.json"
    $(document).ready(function () {
        $('#data').DataTable({
            "language": {
                "url": "/Portuguese.json"
            }
        });
=======
.container-fluid
  .row
    table#data.table.col-md-12.col-xs-12
      thead
        tr
          th =t('activerecord.attributes.school.name')
          th =t('activerecord.attributes.school.code')
          / th =t('activerecord.attributes.school.user')
          th =t('activerecord.attributes.school.total_rooms')
          th =t('activerecord.attributes.school.used_rooms')
          th =t('activerecord.attributes.school.amount_employees')
          th =t('activerecord.attributes.school.technical_or_high_school')
          th
          th
          th

      tbody
        - @schools.each do |school|
          tr
            td =school.name
            td =school.code
            / td =school.user.first_name
            td =school.total_rooms
            td =school.used_rooms
            td =school.amount_employees
            td
              -if school.technical_or_high_school
                p sim
              -else
                p não
            td =link_to school do
              i.fa.fa-eye
            td =link_to edit_school_path(school) do
              i.fa.fa-edit
            td =link_to school, data: {confirm: 'Você tem certeza disso? Esta ação não poderá ser desfeita!'}, method: :delete do
              i.fa.fa-trash.text-danger


javascript:
    //"//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Portuguese.json"
    $(document).ready(function () {
        $('#data').DataTable({
            "language": {
                "url": "/Portuguese.json"
            }
        });
>>>>>>> 34166a1067dc45e0339bcbf35c4f8978d91dd5f3
    });

app/views/schools/new.html.slim
=render 'form'

app/views/schools/show.html.slim
.container-fluid
  .row
    p.col-md-6
      b="#{t('activerecord.attributes.school.name')}: "
      =@school.name

    p.col-md-6
      b="#{t('activerecord.attributes.school.code')}: "
      =@school.code

  .row
    p.col-md-6
      b="#{t('activerecord.attributes.school.coordinator')}: "
      -if @school.coordinator.id.nil?
        =@school.coordinator.full_name
      -if !@school.coordinator.id.nil?
        a href="#{user_path(@school.coordinator.id)}"
          =@school.coordinator.full_name

    p.col-md-6
      b="#{t('activerecord.attributes.school.user')}: "
      a href="#{user_path(@school.user.id)}"
        =@school.user.full_name